default_level = "error"
min_glib_version = "2.78"

ignore = [
    "third-party/**",
    "lib/contrib/**",
]

[style]
space_before_paren = true

[rules.use_g_strcmp0]
ignore =["**"]

[rules.type_style]
ignore =["**"]
