default_level = "error"
min_glib_version = "2.84"

ignore = [
    "third-party/**",
    "lib/contrib/**",
]

[style]
space_before_paren = true

[rules.use_g_strcmp0]
ignore =["**"]

[rules.type_style]
ignore =["**"]

# For the moment disable those rules, needs to be fixed in a follow up MR

[rules.use_auto_cleanup]
ignore =["**"]

[rules.g_source_id_not_stored]
ignore =["**"]

[rules.use_g_object_notify_by_pspec]
ignore =["**"]

[rules.use_g_object_class_install_properties]
ignore =["**"]