.\" Epiphany manpage.
.\" Copyright (C) 2004 GNOME Foundation, Inc.
.\"
.TH EPIPHANY "1" "October 2004" "GNOME" ""
.SH NAME
epiphany \- simple to use web browser
.SH SYNOPSIS
.B epiphany
[\fIOPTION\fR...] [url]
.SH DESCRIPTION
Help options
.TP
-?, \fB\-\-help\fR
Show help message
.TP
\fB\-\-usage\fR
Display brief usage message
.PP
Application options
.TP
\fB\-n\fR, \fB\-\-new\-tab\fR
Open a new tab in an existing
Epiphany window
.TP
\fB\-f\fR, \fB\-\-fullscreen\fR
Run Epiphany in full screen mode
.TP
\fB\-l\fR, \fB\-\-load\-session\fR=\fIFILE\fR
Load the given session file
.TP
\fB\-t\fR, \fB\-\-add\-bookmark\fR=\fIURL\fR
Add a bookmark (don't open any window)
.TP
\fB\-\-import\-bookmarks\fR=\fIFILE\fR
Import bookmarks from the given file
.TP
\fB\-b\fR, \fB\-\-bookmarks\-editor\fR
Launch the bookmarks editor
.TP
\fB\-s\fR, \fB\-\-server\fR
Used internally by the bonobo interface
.PP
Epiphany has a comprehensive help system.  Run the browser
and select \fBHelp\fR from the menu.
.SH AUTHOR
Written by Marco Pesenti Gritti, Christian Persch and others.
