.\" Epiphany manpage.
.\" Copyright © 2006 GNOME Foundation, Inc.
.\"
.TH EPIPHANY "1" "May 2006" "GNOME" ""
.SH NAME
epiphany \- simple to use web browser for GNOME
.SH SYNOPSIS
.B epiphany
[\fIOPTION\fR...] [url]
.SH DESCRIPTION
Help options
.TP
-?, \fB\-\-help\fR
Show help options
.PP
Application options
.TP
\fB\-n\fR, \fB\-\-new\-tab\fR
Open a new tab in an existing
browser window
.TP
\fB\-\-new\-window\fR
Open a new browser window
.TP
\fB\-b\fR, \fB\-\-bookmarks\-editor\fR
Launch the bookmarks editor
.TP
\fB\-\-import\-bookmarks\fR=\fIFILE\fR
Import bookmarks from the given file
.TP
\fB\-l\fR, \fB\-\-load\-session\fR=\fIFILE\fR
Load the given session file
.TP
\fB\-t\fR, \fB\-\-add\-bookmark\fR=\fIURL\fR
Add a bookmark
.TP
\fB\-\-private\-instance\fR
Start a private instance
.TP
\fB\-\-profile\fR=\fIFILE\fR
Profile directory to use in the private instance
.TP
\fB\-\-display\fR=\fIDISPLAY\fR
X display to use
.TP
\fB\-\-version\fR
Show version
.PP
Epiphany has a comprehensive help system.  Run the browser
and select \fBHelp\fR from the menu.
.SH AUTHOR
Written by Marco Pesenti Gritti, Christian Persch and others.
