.\" Epiphany manpage.
.\" Copyright © 2006-2019 GNOME Foundation, Inc.
.\"
.TH EPIPHANY "1" "January 2019"
.SH NAME
epiphany \- a simple, clean, beautiful view of the web
.SH SYNOPSIS
.B epiphany
[\fIOPTION\fR...] [url]
.SH DESCRIPTION
\fBepiphany\fR is the codename of GNOME Web, the web browser designed for the
GNOME desktop and elementary OS.  It offers a simple, clean, beautiful view of
the web featuring first-class GNOME and Pantheon desktop integration, using
WebKitGTK for web rendering.
.SH OPTIONS
.TP
\fB\-\-new\-window\fR
Open a new browser window instead of a new tab
.TP
\fB\-l\fR, \fB\-\-load\-session\fR=\fIFILE\fR
Load the given session state file
.TP
\fB\-i\fR, \fB\-\-incognito\-mode\fR
Start an instance with user data read-only
.TP
\fB\-p\fR, \fB\-\-private\-instance\fR
Start a private instance with separate user data
.TP
\fB\-a\fR, \fB\-\-application\-mode\fR[=\fIBASENAME\fR]
Start a private instance in web application mode (requires passing either desktop file basename or
.B \-\-profile)
.TP
\fB\-\-automation\-mode\fR
Start a private instance for WebDriver control
.TP
\fB\-\-profile\fR=\fIFILE\fR
Custom profile directory for private instance (optional)
.TP
\fB\-\-search\fR \fI[TERM]\fR
Initiate search with given search term
.TP
-?, \fB\-\-help\fR
Show help options
.TP
\fB\-\-version\fR
Show version
.PP
Epiphany has a comprehensive help system.  Run the browser
and select \fBHelp\fR from the menu.
.SH AUTHOR
Written by Marco Pesenti Gritti (in memoriam), Christian Persch, Xan Lopez,
Carlos Garcia Campos, Claudio Saavedra, Michael Catanzaro, Jan-Michael Brummer,
and many others.
