#include <Bonobo.idl>

module GNOME {

	interface EphyAutomation : Bonobo::Unknown {
		void loadurl  (in string  url, 
				  in string  geometry, 
				  in boolean fullscreen,
				  in boolean open_in_existing_tab,
				  in boolean open_in_new_tab,
				  in boolean open_in_new_window,
				  in boolean raise);

		void addBookmark (in string url);

		/**
		 * Closes all opened windows. 
		 * if disableServer is true, 
		 * server mode is disbaled 
		 * (and Epiphany exits)
		 */
		void quit (in boolean disableServer);
		
		void loadSession (in string filename);

		void openBookmarksEditor ();
	};
};

