#include <Bonobo.idl>

module GNOME {

	interface EphyAutomation : Bonobo::Unknown {
		void loadurl  (in string  url, 
		               in boolean fullscreen,
			       in boolean open_in_existing_tab,
			       in boolean open_in_new_tab);

		void addBookmark (in string url);

		void importBookmarks (in string filename);

		void loadSession (in string filename);

		void openBookmarksEditor ();
	};
};

